#Application Configuration
server:
  port: 8084
  
#To see h2 console in browser
#http://localhost:8091/h2-console
#enabling h2 console
spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 #**************************
 #DB configuration
 #*************************
 datasource:
  url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  platform: h2
  username: sa
  password: 
  
  
 #*****************
 #JPA / HIBERNATE
 #^****************
 jpa:
   show-sql: true
   hibernate:
    ddl-auto: update #esto no deberìa ser, solo para demo
   database-platform: org.hibernate.dialect.H2Dialect
   properties:
    hibernate:
     show_sql: true
     use_sql_comments: true
     format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"